[package]
name = "code-name-dune"
version = "0.1.0"
authors = ["Kumar Ankur"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "metal", "json"] }
serde = "*"
specs-physics = "*"
log = "*"
specs-derive = "*"
