[package]
name = "code-name-dune"
version = "0.1.0"
authors = ["Kumar Ankur"]
edition = "2018"

[dependencies]
# amethyst = {version = "0.10.0", features = ["nightly"]}
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "metal"] }
tiled = "0.8.0"
# serde = "*"
